In [13]:
import numpy as np
import pandas as pd

In [18]:
data=pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [33]:
from sklearn.model_selection import train_test_split
X1=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [35]:
from sklearn.preprocessing import scale
X=scale(X1)
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [45]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10)
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(random_state=0)
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [54]:
cv_scores1=cross_val_score(knn, X, y)
cv_scores1

array([0.74025974, 0.74675325, 0.71428571, 0.75816993, 0.73202614])

In [55]:
cv_scores2=cross_val_score(mlp, X, y)
cv_scores2

/home/soumyajeet/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/soumyajeet/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/soumyajeet/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/soumyajeet/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/soumyajeet/.local/lib/python3.

array([0.75974026, 0.74675325, 0.75324675, 0.83006536, 0.77124183])

In [56]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
cv_scores3=cross_val_score(svc, X,y)
cv_scores3

array([0.76623377, 0.75974026, 0.75974026, 0.81699346, 0.76470588])

In [57]:
knn1=np.mean(cv_scores1)
mlp2=np.mean(cv_scores2)
svc3=np.mean(cv_scores3)
accuracy=[]
accuracy.append(knn1)
accuracy.append(mlp2)
accuracy.append(svc3)
accuracy

[0.7382989559460148, 0.7722094898565487, 0.7734827264239028]

In [59]:
a={'knn':accuracy[0],'mlp':accuracy[1],'svc':accuracy[2]}
a

{'knn': 0.7382989559460148,
 'mlp': 0.7722094898565487,
 'svc': 0.7734827264239028}

In [61]:
print('From the method it is clear that SVC linear model has fitted the dataset best')

From the method it is clear that SVC linear model has fitted the dataset best
